#!/bin/python3

import random

def password_generator():
    valid = False

    while (valid == False):
        print("Please enter the password length do you want: ", end = '')
        length = input()
        if (length.isnumeric() == False):
            print("\nPlease enter positive number argument!\n")
            continue
        length = int(length)
        if (length < 12):
            print("\n\033[1m\033[31mAttention, it is recommended for a password to be at least 12 characters long to be secure.\033[0m")
            print("Do you want to continue anyway? [Y/n] ", end = '')
            key = input()
            if (key == '' or key == 'Y' or key == 'y'):
                valid = True
            else:
                print()
        else:
            valid = True

    print("\nHere is your generated password: \"\033[1m\033[96m", end = '')
    for i in range (0, length):
        char = random.randint(33, 126)
        if (char == 48 or char == 49 or char == 73 or char == 79 or char == 108):
            char += 2
        print(f"{char:c}", end = '')
    print("\033[0m\"")

if __name__ == "__main__":
    password_generator()
